### Obtener el pokemon pikachu
GET http://localhost:3000/pokemon/pikachu

### Crear un pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
      "transform"
  ]
}